### ISSUE TITLE
Different Public Key Tokens used for signing <= 2.6.4 and >= 2.6.6

### ISSUE THREAD

**Issue by deenairn** [nunit-legacy/nunitv2#78]
It appears that assemblies within NuGet packages <= 2.6.4 have been signed to create a strong named assembly with a public key token "96d09a1eb7f44a77" and versions >= 2.6.6 have been signed with public key "2638cd05610744eb".

This causes issues where using a signed binary and trying to use an assembly binding redirect, as assembly binding redirects will only work when the assembly has the same public key token. Unfortunately I've got this issue with some assemblies at work where I don't own another library that references NUnit 2.5.9 but would like to upgrade our local project assemblies to 2.7.1 in order to facilitate a future move to NUnit 3+.

i.e. https://stackoverflow.com/questions/2191296/net-assembly-binding-redirect-with-differing-public-key-tokens

I wonder if this was an oversight? I can see why a new public key token was used for NUnit 3.0 assemblies, but those on the legacy line should have the original public key token?

**Comment by CharliePoole** [comment]
Repeating my comment from nunit/nunit#3448...

Because I publish NUnit V2 Legacy (versions after 2.6.4) independent of the NUnit Project, they use a different public key token. Another reason is that the legacy releases are built with newer tools, requiring generation of a new key.

For convenience, both projects are using the same nuget id.

Congrats on being the first person to notice! :smiley:

**Comment by CharliePoole** [comment]
I wasn't aware of the issue with binding redirects before this. However, even if the NUnit Project had chosen to continue maintenance releases of NUnit V2, I think they would have had to generate a new key as soon as they started building it with newer versions of Visual Studio.

If you have any suggestions as to how this can be remedied for a new V2 release, please let me know. Otherwise, you could consider trying to build it yourself from source, substituting the old key and using an old version (IIRC 2013) of VS.

**Comment by CharliePoole** [comment]
@deenairn See the last answer to this question as a possible workaround: https://stackoverflow.com/questions/2191296/net-assembly-binding-redirect-with-differing-public-key-tokens

**Comment by deenairn** [comment]
Hi Charlie, thanks for the very prompt response! 

I think if the same .snk file had been used, the assemblies would be signed with the same public key token. Given they now both have different keys, you would be breaking it for versions >= 2.6.6 if you re-signed using the original .snk for future releases. 

I'll take a look at the StackOverflow post and see if I can hijack the process using, the proposal seems quite simple.

**Comment by CharliePoole** [comment]
My recollection is that the original .snk was unusable when I upgraded the build to use VS2015. It seemed to me that the original "belonged" to the NUnit Project Team, so I simply created new one. I assume that there is some way to create a new-format .snk containing the old key, but I never even tried to do that.

I never thought about binding redirects at the time. In general, I think they should be quite rare WRT tests, since you can just upgrade to the new release anyway. Unfortunately, you are in precisely that rare situation where it's necessary.

If the solution from SO works, please post here so people know about it. If you are able to load, Note that some of the features of the later builds that assist with migration are only visible at compile time, but you should still be able to get a report of issues out by using the new runner.

Something else to try, btw: keep using the 2.5.9 framework but run with the 2.7.1 console runner.

**Comment by CharliePoole** [comment]
Reopening this, now that I understand the impact better.

**Comment by deenairn** [comment]
> @deenairn See the last answer to this question as a possible workaround: https://stackoverflow.com/questions/2191296/net-assembly-binding-redirect-with-differing-public-key-tokens

Today I've been considering how this might happen, but I'm not sure how this would work. As your working with test assemblies and they would be run via the NUnit test runner, it's not easy to see where you would put the "AssemblyResolve" event handler. For example, if it was a Console App, you could do it in the main to ensure it's done before anything else is loaded up, as per the Microsoft example below:

https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.assemblyresolve?view=netframework-4.8

However, as it's the test framework that is initializing the test, I don't think there is an equivalent. It would also need to be in a centralised place so it doesn't need to be copied into every test as using ReSharper, or another tool we can the tests individually. 

In my case I'm using ReSharper and I get the stack in the image below.

![image](https://user-images.githubusercontent.com/3931242/71727541-7edee200-2e32-11ea-9dd7-90ec115633da.png)

**Comment by CharliePoole** [comment]
@deenairn It's been a year since we discussed this and I'm at the point of making additional changes and doing a 2.7.2 release. Where are you on this problem at the moment? Have you managed to figure out some workaround?

**Comment by deenairn** [comment]
Hi @CharliePoole , sorry was using the Android app - makes it too easy to accidentally close issues without confirmation! Pretty sure this is not how GitHub intended! In terms of the v2 NUnit issue above, our internal dependency has been upgraded to v3, so my intention is to upgrade our internal assemblies and NUnit at the same time. Not sure if I should close the issue though? It's not really closed (although it is for me).

**Comment by CharliePoole** [comment]
@deenairn I'm closing it as "won't fix" - thanks for getting back to me.
